---
- hosts: localhost
  run_once: true

  tasks:

    - name: Get ansible date_time fact
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: Create date_time custom fact
      set_fact:
        datestamp: "{{ ansible_date_time.date }}"

    - name: Create directory to store backups
      file:
        path: ~/ansible-network/outputs/backup-config/{{ hostvars.localhost.datestamp }}
        state: directory

- name: Generate backup config files for hosts in the network
  hosts: network
  vars:
    file_path: "~/ansible-network/outputs/backup-config"

  tasks:

    - name: Get EXEC commands output
      register: ios_sh_run
      ios_command:
        commands: "show running-config"

    - name: Backup configs to outputs directory
      delegate_to: localhost
      run_once: false
      copy:
        content: "{{ ios_sh_run.stdout[0] }}"
        dest: "{{ file_path }}/{{ hostvars.localhost.datestamp }}/{{ inventory_hostname }}-sh_run.txt"
