---
- name: Restart Network Configuration
  hosts: core,edge
  tasks:
    - name: Un-configuring Interfaces
      ios_config:
        lines: default interface {{ item.name }}
      loop: "{{ core_l3_links[inventory_hostname] }}"
    - name: Un-configuring OSPF main configuration
      ios_config:
        lines: no router ospf {{ ospf_process }}
    - name: Un-configuring Services Template
      ios_config:
        lines:
          - ip domain lookup
          - service pad
          - no service password-encryption
    - name: Un-configuring SNMP
      ios_config:
        lines: default snmp-server
    - name: Un-configuring Logging
      ios_config:
        lines:
          - default logging host 192.168.0.250
          - default logging source-interface
          - default logging monitor
          - default logging buffered
          - default logging trap
          - default logging console
          - default service timestamps
    - name: Un-configuring NTP
      ios_config:
        lines:
          - default ntp
          - default clock timezone
    - name: Save running-config
      ios_config:
        save_when: modified
