- name: Deploy configuration template on all network devices
  hosts: cisco
  connection: local
  gather_facts: false
  tasks:

    - name: Configure Services
      ios_config:
        lines:
          - no ip domain lookup
          - no service pad
          - service password-encryption
        match: line

    - name: Configure SNMP
      ios_config:
        lines:
          - snmp-server community pragmatico RO
          - snmp-server location DC-LOCATION
          - snmp-server contact pdiazd@gmail.com
          - snmp-server host 192.168.0.250 pragmatico
        before: "default snmp-server"
        match: line

    - name: Configure Logging
      ios_config:
        lines:
          - logging monitor notifications
          - logging buffered 1000000
          - logging trap notifications
          - logging source-interface FastEthernet0/0
          - no logging console
          - service timestamps debug datetime msec localtime show-timezone
          - service timestamps log datetime msec localtime show-timezone
          - logging host 192.168.0.250
        match: line

    - name: Configure Time and NTP
      ios_config:
        lines:
          - clock timezone CLST -3 0
          - ntp source FastEthernet0/0
          - ntp update-calendar
          - ntp server 192.168.0.250
        match: line

    - name: Save running to startup when modified
      ios_config:
        save_when: modified
